import { useLocation, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Shield, Award, Download, CheckCircle, Hash, Calendar, FileText, Search } from 'lucide-react'
import { useState, useEffect } from 'react'
import { historyService } from '../utils/historyService'
import type { ScanHistoryItem } from '../utils/historyService'

export default function CertificatePage() {

  const location = useLocation()
  const navigate = useNavigate()
  const [result, setResult] = useState<any>(location.state?.result)
  const [loading, setLoading] = useState(false)
  const [searchId, setSearchId] = useState('')

  useEffect(() => {
    if (result) return
    // Maybe try to load latest authentic scan if none provided?
    const scans = historyService.getScans()
    const latestAuthentic = scans.find(s => s.result === 'AUTHENTIC' || s.result === 'VERIFIED')
    if (latestAuthentic) {
      // For certificates, we need the full generation metadata which we don't save in history yet
      // This is a gap. Let's make generateDeterministicResult accessible or save it.
    }
  }, [result])

  const handleSearch = () => {
    setLoading(true)
    setTimeout(() => {
      const scan = historyService.getScans().find(s => s.id === searchId || s.id.includes(searchId))
      if (scan && (scan.result === 'AUTHENTIC' || scan.result === 'VERIFIED' || scan.score > 80)) {
        // Reconstruct a result object for the UI
        setResult({
          antigravity: {
            truthScore: scan.score,
            verdict: scan.result,
            caseId: scan.id,
            mediaType: scan.type,
            certificate: {
              sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
              issuedAt: scan.timestamp
            },
            explanation: { legal: 'This media has been verified as authentic by AntiGravity AI.' }
          }
        })
      }
      setLoading(false)
    }, 800)
  }

  const handleDownload = () => {
    if (!result?.antigravity) return
    const { truthScore, verdict, caseId, certificate, mediaType } = result.antigravity
    // HTML-based certificate download
  const certHtml = `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: 'Arial', sans-serif; background: #0A0E1A; color: #E8EDF5; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
  .cert { background: linear-gradient(135deg, #0D1225, #111827); border: 2px solid #00F5FF40; border-radius: 16px; padding: 60px; max-width: 700px; text-align: center; box-shadow: 0 0 60px rgba(0,245,255,0.15); }
  h1 { font-size: 32px; color: #00F5FF; margin-bottom: 8px; text-shadow: 0 0 20px rgba(0,245,255,0.5); }
  .sub { color: #8B9AB5; font-size: 14px; margin-bottom: 40px; }
  .score { font-size: 72px; font-weight: bold; color: #00FF88; }
  .verdict { background: rgba(0,255,136,0.15); border: 1px solid #00FF8830; padding: 8px 20px; border-radius: 8px; display: inline-block; margin: 16px 0; color: #00FF88; }
  .detail { background: #0A0E1A; padding: 20px; border-radius: 8px; margin: 24px 0; text-align: left; }
  .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #1E2D4A; font-size: 13px; }
  .label { color: #8B9AB5; } .val { color: #00F5FF; font-family: monospace; }
  .footer { color: #4A5770; font-size: 12px; margin-top: 30px; }
</style>
</head>
<body>
<div class="cert">
  <h1>ANTIGRAVITY</h1>
  <p class="sub">AI-Powered Media Authenticity Certificate — India Cyber Cell</p>
  <div class="score">${truthScore}</div>
  <p style="color:#8B9AB5; margin-top:-10px">TruthScore™</p>
  <div class="verdict">✓ ${verdict}</div>
  <div class="detail">
    <div class="row"><span class="label">Case ID</span><span class="val">${caseId}</span></div>
    <div class="row"><span class="label">SHA-256 Hash</span><span class="val">${certificate.sha256.slice(0, 32)}...</span></div>
    <div class="row"><span class="label">Media Type</span><span class="val">${mediaType}</span></div>
    <div class="row"><span class="label">Analysis Date</span><span class="val">${new Date(certificate.issuedAt).toLocaleDateString('en-IN')}</span></div>
  </div>
  <p class="footer">This certificate is digitally generated by AntiGravity Platform v2.1. Signature anchored to forensic ledger.</p>
</div>
</body>
</html>`
    const blob = new Blob([certHtml], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${result.caseId}_certificate.html`
    a.click()
  }

  if (!result?.antigravity) {
    return (
      <div className="max-w-xl mx-auto space-y-6">
        <div className="rounded-2xl p-8 text-center" style={{ background: '#0D1225', border: '1px solid #1E2D4A' }}>
          <Award size={48} style={{ color: '#1E2D4A' }} className="mx-auto mb-4" />
          <h2 className="text-xl font-bold mb-2" style={{ fontFamily: 'Syne, sans-serif' }}>Certificate Registry</h2>
          <p className="text-sm text-[#8B9AB5] mb-6">Enter a Case ID to retrieve a verified authenticity certificate.</p>
          
          <div className="flex gap-2">
            <input 
              type="text" 
              placeholder="Case ID (e.g. AG-12345)"
              value={searchId}
              onChange={e => setSearchId(e.target.value)}
              className="flex-1 px-4 py-3 rounded-xl outline-none"
              style={{ background: '#0A0E1A', border: '1px solid #1E2D4A', color: '#E8EDF5', fontFamily: 'JetBrains Mono, monospace' }}
            />
            <button 
              onClick={handleSearch}
              disabled={loading}
              className="px-6 py-3 rounded-xl font-bold text-sm"
              style={{ background: 'linear-gradient(135deg, #00F5FF, #0066CC)', color: '#0A0E1A', fontFamily: 'Syne, sans-serif' }}
            >
              {loading ? '...' : 'Retrieve'}
            </button>
          </div>
        </div>

        <div className="flex flex-col items-center justify-center p-8 text-center opacity-50">
          <p className="text-xs" style={{ color: '#4A5770', fontFamily: 'JetBrains Mono, monospace' }}>
            Only media with TruthScore &gt; 80% are eligible for official certification.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-2xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-2xl overflow-hidden"
        style={{ border: '1px solid #00FF8830', boxShadow: '0 0 40px rgba(0, 255, 136, 0.1)' }}
      >
        {/* Header */}
        <div
          className="p-6 text-center"
          style={{ background: 'linear-gradient(135deg, #0D1225, #091520)', borderBottom: '1px solid #00FF8830' }}
        >
          <div className="flex justify-center mb-4">
            <div
              className="w-16 h-16 rounded-2xl flex items-center justify-center"
              style={{ background: 'rgba(0,255,136,0.1)', border: '1px solid #00FF8840' }}
            >
              <Award size={32} style={{ color: '#00FF88' }} />
            </div>
          </div>
          <h2 className="text-xl font-bold mb-1" style={{ fontFamily: 'Syne, sans-serif', color: '#E8EDF5' }}>
            AUTHENTICITY CERTIFICATE
          </h2>
          <p className="text-xs" style={{ color: '#8B9AB5', fontFamily: 'JetBrains Mono, monospace' }}>
            AntiGravity Intelligence Platform — India Cyber Cell
          </p>
        </div>

        {/* Score Display */}
        <div
          className="p-8 text-center"
          style={{ background: '#0D1225' }}
        >
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ delay: 0.2, type: 'spring' }}
          >
            <div className="text-6xl font-bold mb-2" style={{ color: '#00FF88', fontFamily: 'JetBrains Mono, monospace', textShadow: '0 0 30px rgba(0,255,136,0.5)' }}>
              {result.antigravity.truthScore}
            </div>
            <p className="text-sm mb-3" style={{ color: '#8B9AB5', fontFamily: 'JetBrains Mono, monospace' }}>TruthScore™</p>
            <span
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-bold"
              style={{ background: 'rgba(0,255,136,0.15)', color: '#00FF88', border: '1px solid #00FF8830', fontFamily: 'Syne, sans-serif' }}
            >
              <CheckCircle size={16} />
              CERTIFIED AUTHENTIC
            </span>
          </motion.div>
        </div>

        {/* Details */}
        <div className="p-6" style={{ background: '#0A0E1A', borderTop: '1px solid #1E2D4A' }}>
          <div className="space-y-3">
            {[
              { icon: Shield, label: 'Case ID', value: result.antigravity.caseId },
              { icon: Hash, label: 'SHA-256 Hash', value: `${result.antigravity.certificate.sha256.slice(0, 32)}...` },
              { icon: FileText, label: 'Media Type', value: result.antigravity.mediaType },
              { icon: Calendar, label: 'Verified On', value: new Date(result.antigravity.certificate.issuedAt).toLocaleString('en-IN') },
            ].map(({ icon: Icon, label, value }) => (
              <div
                key={label}
                className="flex items-center gap-3 p-3 rounded-lg"
                style={{ background: '#0D1225', border: '1px solid #1E2D4A' }}
              >
                <Icon size={14} style={{ color: '#00F5FF', flexShrink: 0 }} />
                <span className="text-xs" style={{ color: '#8B9AB5', fontFamily: 'JetBrains Mono, monospace', minWidth: 120 }}>{label}</span>
                <span className="text-xs font-mono ml-auto text-right" style={{ color: '#00F5FF', fontFamily: 'JetBrains Mono, monospace', wordBreak: 'break-all' }}>{value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Download */}
        <div className="p-6" style={{ background: '#0D1225', borderTop: '1px solid #1E2D4A' }}>
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.97 }}
            onClick={handleDownload}
            className="w-full py-4 rounded-xl font-bold text-sm flex items-center justify-center gap-2"
            style={{ background: 'linear-gradient(135deg, #00FF88, #00AA55)', color: '#0A0E1A', fontFamily: 'Syne, sans-serif', boxShadow: '0 0 25px rgba(0,255,136,0.3)' }}
          >
            <Download size={18} />
            DOWNLOAD CERTIFICATE
          </motion.button>
        </div>
      </motion.div>
    </div>
  )
}
